
apiVersion: v1
kind: Service
metadata:
  name: neuvector-service-registry-adapter
  namespace: neuvector
spec:
  ports:
  - port: 9443
    name: registry-adapter
    protocol: TCP
  type: LoadBalancer
  selector:
    app: neuvector-registry-adapter-pod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuvector-registry-adapter-pod
  namespace: neuvector
spec:
  selector:
    matchLabels:
      app: neuvector-registry-adapter-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: neuvector-registry-adapter-pod
    spec:
      serviceAccount: registry-adapter
      serviceAccountName: registry-adapter
      containers:
        - name: neuvector-registry-adapter-pod
          image: neuvector/registry-adapter:0.1.3
          imagePullPolicy: Always
          env:
            - name: CLUSTER_JOIN_ADDR
              value: neuvector-svc-controller.neuvector
            - name: HARBOR_SERVER_PROTO
              value: https
            - name: HARBOR_BASIC_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: neuvector-registry-adapter
                  key: username
            - name: HARBOR_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neuvector-registry-adapter
                  key: password
      restartPolicy: Always
